name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was triggered by a ${{ github.event_name }} event."

      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup Go v.1.21
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.0

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - name: Test
        run: go test -short -race -vet=off ./...

      - run: echo "This job's status is ${{ job.status }}"
